version: '3.8'

services:
  db:
    image: postgres:15
    container_name: housing_db_container
    restart: always
    environment:
      POSTGRES_USER: housing
      POSTGRES_PASSWORD: inspection
      POSTGRES_DB: housing_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: ../docker/Dockerfile
    container_name: housing_backend_container
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    depends_on:
      - db
    volumes:
      - ./backend/app:/app/app
      - ./backend/uploads:/app/uploads

volumes:
  postgres_data: